---
- name: ping them all
  # hosts: _servers
  hosts: aws_ec2
  vars:
    ansible_user: "ubuntu"
    ansible_ssh_private_key_file: "/home/arc/ansible/aws-keypair/it.pem"
  tasks:
    - name: pinging
      ping: