server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.251.203:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx-access
      __path__: /usr/local/openresty/nginx/logs/80-access.log
      host: ${HOSTNAME}
      agent: promtail